### ISSUE TITLE
[BUG] Relations doesn't work whith JSON API v3.0.7 ans Bolt 3.2.3

### ISSUE THREAD

**Issue by brethymnis** [xiaohutai/jsonapi#37] opened 2016-12-16 10:18 UTC
Hi, 

When a want to export JSON with this contenttype : 
actus:

    name: Actualites
    singular_name: Actualite
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: text
            class: large
            pattern: ".{0,140}" # see: http://html5pattern.com/
        body:
            type: html
            height: 300px
        checkbox:
            type: checkbox
            label: "Afficher l'actualité dans la page des actualités"
    relations:
        pages:
            multiple: true
            order: title
            label: Sélectionnez une ou plusieurs pages où sera affiché l'actualité
    record_template: entry-actu.twig
    listing_template: listing-actus.twig
    listing_records: 10
    default_status: publish
    sort: datepublish DESC
    recordsperpage: 10
    icon_many: "fa:info-circle"
    icon_one: "fa:info-circle"

It displays : 

> Uncaught Exception: ContextErrorException

ContextErrorException in Parser.php line 77:
Catchable Fatal Error: Object of class Bolt\Storage\Collection\LazyCollection could not be converted to string

                }

                // Handle replacements.
                if (!empty($this->config->getReplacements())) {
                    foreach ($this->config->getReplacements() as $from => $to) {
                        $item = str_replace($from, $to, $item);
                    }
                }
            });

            $values['attributes'] = $attributes;

I delete relation ans it's work ...
relation is deprieciated ?

**Comment by mamoot64** [comment] 2017-01-04 09:05
I confirm the bug. JSON API version 3.0.7 is broken with BOLT v3.2.3 / v3.2.4

`ContextErrorException in Parser.php line 77: 
Catchable Fatal Error: Object of class Bolt\Storage\Collection\LazyCollection could not be converted to string`

**Comment by mamoot64** [comment] 2017-01-17 16:26
Hi,

I have commented this lines in configuration :

```
#replacements:
#    'src="//': 'src="http://'
#    'href="//': 'href="http://'
```

It's work's great now !

**Comment by Raistlfiren** [comment] 2017-03-20 21:17
@acidline and @brethymnis - Can you please check to see if the problem exists in the latest version?

**Comment by brethymnis** [comment] 2017-03-21 09:34
It's work with the latest version :-) 👍 
But doesn't with with 10 000 entries : Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 3221128 bytes) 
But I think it's the configuration of my test server

**Comment by Raistlfiren** [comment] 2017-03-21 09:59
Yeah that is definitely a server configuration. Check your max memory config for PHP.

**Comment by brethymnis** [comment] 2017-03-21 10:01
;-)

**Comment by GwendolenLynch** [comment] 2017-03-21 10:04
That's why my `php.ini` always has the setting `memory_limit = 1.21 gigawatts`

**Comment by Raistlfiren** [comment] 2017-03-21 13:38
I am closing this issue because I think the problem is now resolved. Feel free to respond back here if it isn't.

**Closed as completed by Raistlfiren** 2017-03-21 13:38 UTC
